### ISSUE TITLE
getController 가 제대로 작동하지 않음. (FXMLLoader)

### ISSUE THREAD

**Issue by minseungkang** [minseungkang/DPProject2016_MusicPlayer#5]
제곧내

**Comment by lyuha** [comment]
> You first have to run loader.load() then you can get the Controller.

[FXMLLoader getController returns NULL?](http://stackoverflow.com/a/23461254)

**Comment by lyuha** [comment]
Commit c2ad5dde8fa9d198c2ed00b28a2347d4b53d0627
